test: integration testing and ci
MapColonies/retiler pull request #13
Opened 2022-04-14 12:56 UTC by melancholiai

| Question                | Answer                                                                          |
| ---------------- | -------------------------------------------------------------------------- |
| Bug fix         | ✖                                                                        |
| New feature     | ✖                                                                        |
| Breaking change | ✖                                                                        |
| Deprecations    | ✖                                                                        |
| Documentation   | ✖                                                                        |
| Tests added     | ✔                                                                        |
| Chore            | ✖                                                                       |

2022-04-17 04:32 UTC, CptSchnitz requested changes

2022-04-17 04:32 UTC, CptSchnitz commented on .github/workflows/pull_request.yaml
> +        image: bitnami/minio:latest
dont use latest

2022-04-17 04:32 UTC, CptSchnitz commented on commitlint.config.js
> +        "scope-enum": [2, "always", ["deps", "configurations", "ci"]],
pretty sure "ci" is not needed here as its a type and not a scope.

2022-04-17 04:32 UTC, CptSchnitz commented on src/app.ts
> +export async function runApp(container: DependencyContainer): Promise<void> {
it would be nice to have a better name

2022-04-17 04:32 UTC, CptSchnitz commented on src/index.ts
> +    await runApp(container);
both of those should be in containerConfig as factories.

2022-04-17 12:25 UTC, melancholiai commented on .github/workflows/pull_request.yaml
> +        image: bitnami/minio:latest
done.

2022-04-17 12:25 UTC, melancholiai commented on commitlint.config.js
> +        "scope-enum": [2, "always", ["deps", "configurations", "ci"]],
done.

2022-04-17 12:25 UTC, melancholiai commented on src/app.ts
> +export async function runApp(container: DependencyContainer): Promise<void> {
done.

2022-04-17 12:26 UTC, melancholiai commented on src/index.ts
> +    await runApp(container);
done.

2022-04-18 07:02 UTC, CptSchnitz approved these changes

2022-04-18 07:40 UTC, merged