docs: updated readme
MapColonies/retiler pull request #14
Opened 2022-04-17 08:59 UTC by melancholiai

| Question                | Answer                                                                          |
| ---------------- | -------------------------------------------------------------------------- |
| Bug fix         | ✖                                                                        |
| New feature     | ✖                                                                        |
| Breaking change | ✖                                                                        |
| Deprecations    | ✖                                                                        |
| Documentation   | ✔                                                                        |
| Tests added     | ✖                                                                        |
| Chore            | ✖                                                                       |

2022-04-17 09:13 UTC, CptSchnitz requested changes

2022-04-17 09:13 UTC, CptSchnitz commented on README.md
> +retiler is a service intended to run as a [k8s job](https://kubernetes.io/docs/concepts/workloads/controllers/job/).
no reason to mention k8s job, you can just use npm start and it will work exactly the same

2022-04-17 09:13 UTC, CptSchnitz commented on README.md
> +finally the tiles will be stored on s3 storage.
1. Capitalize first word in a sentence.
2. The explanation can be expanded a bit more, and be more clear. (for example: why the tiles are splitted, which endpoint is used on arcgis, etc..)
3. A diagram could be nice.

2022-04-17 13:23 UTC, melancholiai commented on README.md
> +retiler is a service intended to run as a [k8s job](https://kubernetes.io/docs/concepts/workloads/controllers/job/).
done.

2022-04-17 13:23 UTC, melancholiai commented on README.md
> +finally the tiles will be stored on s3 storage.
done.

2022-04-18 07:12 UTC, CptSchnitz approved these changes
Mermaid looks good :)

2022-04-18 07:38 UTC, merged