feat!: multi tile storage destinations including fs
MapColonies/retiler pull request #30
Opened 2023-10-03 09:32 UTC by melancholiai

| Question                | Answer                                                                          |
| ---------------- | -------------------------------------------------------------------------- |
| Bug fix         | ✖                                                                        |
| New feature     | ✔                                                                        |
| Breaking change | ✔                                                                        |
| Deprecations    | ✖                                                                        |
| Documentation   | ✔                                                                        |
| Tests added     | ✔                                                                        |
| Chore            | ✖                                                                       |

2023-11-14 19:48 UTC, syncush requested changes

2023-11-14 19:48 UTC, syncush commented on config/custom-environment-variables.json
> +        "__format": "json"
we can't validate its schema right?

2023-11-14 19:48 UTC, syncush commented on src/index.ts
> +        return new Promise((resolve) => {
shouldnt we use `server.drain` also ?

2023-11-14 19:48 UTC, syncush commented on src/retiler/jobQueueProvider/pgBossJobQueue.ts
> +  private readonly jobFinishedEventName = 'jobFinished';
unacceptable!

2023-11-14 19:48 UTC, syncush commented on src/retiler/tilesStorageProvider/factory.ts
> +              resolve(undefined);
isn't it better to return `resolve(undefined);`?

2023-11-14 19:48 UTC, syncush commented on src/retiler/tilesStorageProvider/fs.ts
> +      }
should we make a dir on our own ? what about permissions and so on, I think the server should fail if path does not exists or is not writeable or readable. we should not change the state of the storage.

2023-11-14 19:48 UTC, syncush commented on tests/configurations/integration/jest.config.js
> +      statements: -20,
do we have a reason to lower the standard?

2023-11-15 12:12 UTC, melancholiai commented on config/custom-environment-variables.json
> +        "__format": "json"
added ajv on the factory function

2023-11-15 12:12 UTC, melancholiai commented on src/index.ts
> +        return new Promise((resolve) => {
no such function

2023-11-15 12:12 UTC, melancholiai commented on src/retiler/jobQueueProvider/pgBossJobQueue.ts
> +  private readonly jobFinishedEventName = 'jobFinished';
sorry ;(

2023-11-15 12:12 UTC, melancholiai commented on src/retiler/tilesStorageProvider/factory.ts
> +              resolve(undefined);
done.

2023-11-15 12:12 UTC, melancholiai commented on src/retiler/tilesStorageProvider/fs.ts
> +      }
the tiles storage dir is set according to the fs storageProvider's `basePath` + `app.tilesStorage.layout.format` configuration value, the latter value changes from time to time.
I don't see a downside to attempt to create the dir, remember it also creates the `z/x/y` directories.
another manual step is another pain in the ass, and anyway if there are insufficient permissions to write the file the job will fail with a proper error.

2023-11-15 12:12 UTC, melancholiai commented on tests/configurations/integration/jest.config.js
> +      statements: -20,
done, I've added a couple of tests to achieve the standard

2023-11-20 18:27 UTC, syncush approved these changes

2023-11-24 14:07 UTC, merged