feat: axios injection and configurable config
MapColonies/retiler pull request #4
Opened 2022-03-27 15:04 UTC by melancholiai

| Question                | Answer                                                                          |
| ---------------- | -------------------------------------------------------------------------- |
| Bug fix         | ✖                                                                        |
| New feature     | ✔                                                                        |
| Breaking change | ✖                                                                        |
| Deprecations    | ✖                                                                        |
| Documentation   | ✖                                                                        |
| Tests added     | ✔                                                                        |
| Chore            | ✖                                                                       |

2022-03-27 15:30 UTC, CptSchnitz requested changes
prettier for files changed

2022-03-27 15:30 UTC, CptSchnitz commented on config/default.json
> +        "timeout": 1000
the default should be way larger - at least 30,000ms, maybe even 60,000ms

2022-03-27 15:30 UTC, CptSchnitz commented on config/custom-environment-variables.json
> +        "timeout": {
change it to indicate its time in miliseconds

2022-03-27 15:30 UTC, CptSchnitz commented on src/retiler/mapProvider/constants.ts
> +export const GET_MAP_PARAMS = {
it should be arcgis map params.

2022-03-28 07:24 UTC, melancholiai commented on config/default.json
> +        "timeout": 1000
done.

2022-03-28 07:24 UTC, melancholiai commented on config/custom-environment-variables.json
> +        "timeout": {
Axios expects an argument named timeout (which is on ms), I suggest it will be described in the docs instead of on key name

2022-03-28 07:24 UTC, melancholiai commented on src/retiler/mapProvider/constants.ts
> +export const GET_MAP_PARAMS = {
done.

2022-03-28 08:04 UTC, CptSchnitz approved these changes

2022-03-28 08:20 UTC, merged