refactor: map provider and splitter works on buffer instead of stream
MapColonies/retiler pull request #5
Opened 2022-03-29 11:01 UTC by melancholiai

| Question                | Answer                                                                          |
| ---------------- | -------------------------------------------------------------------------- |
| Bug fix         | ✖                                                                        |
| New feature     | ✖                                                                        |
| Breaking change | ✖                                                                        |
| Deprecations    | ✖                                                                        |
| Documentation   | ✖                                                                        |
| Tests added     | ✔                                                                        |
| Chore            | ✖                                                                       |

2022-03-29 12:44 UTC, CptSchnitz requested changes

2022-03-29 12:44 UTC, CptSchnitz commented on src/retiler/interfaces.ts
> +  getMapBuffer: (bbox: BoundingBox, mapWidth: number, mapHeight: number) => Promise<Buffer>;
change to get map

2022-03-29 12:44 UTC, CptSchnitz commented on src/retiler/mapSplitterProvider/sharp.ts
> +    const stream = bufferToStream(buffer);
?

2022-03-29 13:19 UTC, melancholiai commented on src/retiler/mapSplitterProvider/sharp.ts
> +    const stream = bufferToStream(buffer);
done.

2022-03-29 13:19 UTC, melancholiai commented on src/retiler/interfaces.ts
> +  getMapBuffer: (bbox: BoundingBox, mapWidth: number, mapHeight: number) => Promise<Buffer>;
done.

2022-03-30 11:03 UTC, CptSchnitz approved these changes

2022-03-30 13:57 UTC, merged