feat: improved storage layout and splitter filtering out of bounds
MapColonies/retiler pull request #6
Opened 2022-03-30 14:07 UTC by melancholiai

| Question                | Answer                                                                          |
| ---------------- | -------------------------------------------------------------------------- |
| Bug fix         | ✖                                                                        |
| New feature     | ✔                                                                        |
| Breaking change | ✔                                                                        |
| Deprecations    | ✖                                                                        |
| Documentation   | ✖                                                                        |
| Tests added     | ✔                                                                        |
| Chore            | ✖                                                                       |

2022-03-30 14:48 UTC, CptSchnitz requested changes
update readme with the new layout config

2022-03-30 14:48 UTC, CptSchnitz commented on src/retiler/util.ts
> +};
maybe we should use the validateTile function from tile-calc

2022-03-30 14:48 UTC, CptSchnitz commented on config/custom-environment-variables.json
> +        "shouldReverseY": {
maybe it should called flipped instead of reverse. (or let the user choose if the tiles root is lower left or upper left.

2022-03-30 15:04 UTC, melancholiai commented on src/retiler/util.ts
> +};
an invalid tile will throw an error, should we use it like this?
```
const isTileOutOfBounds = (tile: Tile): boolean => {
  try {
    validateTile(tile, TILEGRID_WORLD_CRS84);
    return true;
  } catch (err) {
    return false;
  }
}
```

2022-03-31 09:12 UTC, melancholiai commented on src/retiler/mapSplitterProvider/sharp.ts
> +        const splittedTile = { z: tile.z, x: tile.x * splitsPerAxis + column, y: tile.y * splitsPerAxis + row, metatile: 1 };
done.

2022-03-31 09:12 UTC, melancholiai commented on src/retiler/util.ts
> +};
done.

2022-04-03 15:45 UTC, CptSchnitz approved these changes

2022-04-04 09:28 UTC, merged